name: Build and Push to GHCR

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build the image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest -f apps/financial-dashboard

      - name: Push the image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:latest
        env:
          DOCKER_BUILDKIT: 1
